// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6zOSC75qFZCHNjctlfj67oLx4FCXtGU',
    appId: '1:189491346512:web:8d14e2b5209bde7238a555',
    messagingSenderId: '189491346512',
    projectId: 'jr-call',
    authDomain: 'jr-call.firebaseapp.com',
    storageBucket: 'jr-call.firebasestorage.app',
    measurementId: 'G-2SPHN3RMT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCw2QZY20mLArqLq99yqIEFVtqz9HC-7Y',
    appId: '1:189491346512:android:442b874d29bfa58c38a555',
    messagingSenderId: '189491346512',
    projectId: 'jr-call',
    storageBucket: 'jr-call.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbHfnzj7h7lhwbOQ9EEFZo6KnB0YAYzWQ',
    appId: '1:189491346512:ios:0ddf9c490c244b2a38a555',
    messagingSenderId: '189491346512',
    projectId: 'jr-call',
    storageBucket: 'jr-call.firebasestorage.app',
    iosBundleId: 'com.example.jrCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbHfnzj7h7lhwbOQ9EEFZo6KnB0YAYzWQ',
    appId: '1:189491346512:ios:0ddf9c490c244b2a38a555',
    messagingSenderId: '189491346512',
    projectId: 'jr-call',
    storageBucket: 'jr-call.firebasestorage.app',
    iosBundleId: 'com.example.jrCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs6zOSC75qFZCHNjctlfj67oLx4FCXtGU',
    appId: '1:189491346512:web:3fc25bdc0cb9319738a555',
    messagingSenderId: '189491346512',
    projectId: 'jr-call',
    authDomain: 'jr-call.firebaseapp.com',
    storageBucket: 'jr-call.firebasestorage.app',
    measurementId: 'G-SSDSWF133Y',
  );
}
