// ===============================================================
// JR CALL
// File: call_listener_service.dart
// Location: lib/services/call/call_listener_service.dart
//
// MASTER PRODUCTION CALL-DOCUMENT LISTENER
//
// Ownership:
// - SignalingService -> Firestore call-document access.
// - CallListenerService -> ordered call-document observation only.
// - CallService -> complete call lifecycle/orchestration.
// - WebRTCService -> PeerConnection/media/SDP transport.
// - IceManager -> local + remote ICE synchronization.
// - RecoveryManager -> call recovery.
//
// Production guarantees:
// - Exactly one CURRENT Firestore call listener.
// - Superseded subscription callbacks are rejected.
// - Stale call-session callbacks are rejected.
// - Terminal status cannot be lost during listener shutdown.
// - Terminal events cannot leak into a later call.
// - Duplicate Firestore values are filtered.
// - Offer/answer values are validated.
// - Events are delivered in deterministic order.
// - Reconnect uses bounded exponential backoff.
// - Permanent Firestore errors are NOT blindly retried.
// - Transient listener failures may recover safely.
// - No Firestore writes here.
// - No WebRTC ownership here.
// - No ICE ownership here.
// - No call-lifecycle ownership here.
// ===============================================================

import 'dart:async';
import 'dart:collection';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

import 'signaling_service.dart';

// ===============================================================
// FIRESTORE CALL FIELD CONSTANTS
// ===============================================================

abstract final class CallFields {
  static const String status = 'status';
  static const String offer = 'offer';
  static const String answer = 'answer';

  static const String connectionState = 'connectionState';
  static const String iceConnectionState = 'iceConnectionState';
  static const String signalingState = 'signalingState';
  static const String iceGatheringState = 'iceGatheringState';

  static const String networkRecovered = 'networkRecovered';
  static const String iceRestartCount = 'iceRestartCount';

  static const String sdp = 'sdp';
  static const String type = 'type';
}

// ===============================================================
// CALL STATUS VALUES
// ===============================================================

abstract final class CallStatusValues {
  static const String calling = 'calling';
  static const String ringing = 'ringing';
  static const String connecting = 'connecting';
  static const String connected = 'connected';
  static const String reconnecting = 'reconnecting';

  static const String ended = 'ended';
  static const String rejected = 'rejected';
  static const String declined = 'declined';
  static const String cancelled = 'cancelled';
  static const String failed = 'failed';
  static const String timeout = 'timeout';

  static bool isTerminal(String status) {
    switch (status.trim().toLowerCase()) {
      case ended:
      case rejected:
      case declined:
      case cancelled:
      case failed:
      case timeout:
        return true;

      default:
        return false;
    }
  }
}

// ===============================================================
// INTERNAL EVENT TYPE
// ===============================================================

enum _CallListenerEventType {
  status,
  offer,
  answer,
  connectionState,
  iceConnectionState,
  signalingState,
  iceGatheringState,
  networkRecovered,
  iceRestart,
  callEnded,
  callDeleted,
}

// ===============================================================
// ORDERED INTERNAL EVENT
// ===============================================================

class _CallListenerEvent {
  const _CallListenerEvent({
    required this.type,
    required this.sessionToken,
    required this.callId,
    this.payload,
    this.deliverAfterTermination = false,
  });

  final _CallListenerEventType type;

  final int sessionToken;

  final String callId;

  final Object? payload;

  /// Only terminal events generated by the exact terminating
  /// call/session may survive synchronous listener invalidation.
  final bool deliverAfterTermination;
}

// ===============================================================
// CALL LISTENER SERVICE
// ===============================================================

class CallListenerService {
  CallListenerService._();

  static final CallListenerService instance = CallListenerService._();

  // =============================================================
  // SERVICES
  // =============================================================

  final SignalingService _signalingService = SignalingService.instance;

  // =============================================================
  // RECONNECT CONFIGURATION
  // =============================================================

  static const int _maximumReconnectAttempts = 5;

  static const Duration _initialReconnectDelay = Duration(seconds: 2);

  static const Duration _maximumReconnectDelay = Duration(seconds: 30);

  // =============================================================
  // ACTIVE SESSION
  // =============================================================

  String? currentCallId;

  StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>?
  currentSubscription;

  bool isListening = false;

  bool _isDisposed = false;

  bool _isPaused = false;

  bool _isProcessingQueue = false;

  bool _isReconnectScheduled = false;

  bool _isReportingError = false;

  int _sessionGenerationId = 0;

  /// Distinguishes replacement subscriptions inside the SAME
  /// call session.
  ///
  /// This is separate from _sessionGenerationId because a reconnect
  /// should keep the same call session while invalidating callbacks
  /// from the previous Firestore subscription.
  int _subscriptionGenerationId = 0;

  int _reconnectAttempts = 0;

  Timer? _reconnectTimer;

  // =============================================================
  // TERMINATED SESSION IDENTITY
  // =============================================================

  int? _terminatedSessionToken;

  String? _terminatedCallId;

  // =============================================================
  // DETERMINISTIC EVENT QUEUE
  // =============================================================

  final Queue<_CallListenerEvent> _eventQueue = Queue<_CallListenerEvent>();

  // =============================================================
  // LAST OBSERVED VALUES
  // =============================================================

  String? lastStatus;

  Map<String, dynamic>? lastOffer;

  Map<String, dynamic>? lastAnswer;

  String? _lastConnectionState;

  String? _lastIceConnectionState;

  String? _lastSignalingState;

  String? _lastIceGatheringState;

  bool _lastNetworkRecovered = false;

  int _lastIceRestartCount = 0;

  // =============================================================
  // PUBLIC CALLBACKS
  // =============================================================

  ValueChanged<String>? onStatusChanged;

  ValueChanged<Map<String, dynamic>>? onOfferReceived;

  ValueChanged<Map<String, dynamic>>? onAnswerReceived;

  VoidCallback? onCallEnded;

  VoidCallback? onCallDeleted;

  ValueChanged<String>? onConnectionStateChanged;

  ValueChanged<String>? onIceConnectionStateChanged;

  ValueChanged<String>? onSignalingStateChanged;

  ValueChanged<String>? onIceGatheringStateChanged;

  VoidCallback? onNetworkRecovered;

  VoidCallback? onIceRestart;

  ValueChanged<Object>? onError;

  // =============================================================
  // PUBLIC STATE
  // =============================================================

  bool get isDisposed => _isDisposed;

  bool get isPaused => _isPaused;

  int get reconnectAttempts => _reconnectAttempts;

  // =============================================================
  // REINITIALIZATION
  // =============================================================

  void initialize() {
    if (!_isDisposed) {
      return;
    }

    _isDisposed = false;

    _isPaused = false;

    _isReconnectScheduled = false;

    _reconnectAttempts = 0;

    _terminatedSessionToken = null;

    _terminatedCallId = null;
  }

  // =============================================================
  // START LISTENING
  // =============================================================

  void startListening(String callId) {
    final String normalizedCallId = callId.trim();

    if (_isDisposed) {
      _reportError(
        StateError(
          'CallListenerService is disposed. '
          'Call initialize() before reusing it.',
        ),
        source: 'startListening',
      );

      return;
    }

    if (normalizedCallId.isEmpty) {
      _reportError(
        ArgumentError.value(callId, 'callId', 'Call ID cannot be empty.'),
        source: 'startListening',
      );

      return;
    }

    if (isListening &&
        currentCallId == normalizedCallId &&
        currentSubscription != null) {
      return;
    }

    _stopActiveSession(clearQueue: true, clearCachedValues: true);

    final int sessionToken = ++_sessionGenerationId;

    currentCallId = normalizedCallId;

    isListening = true;

    _isPaused = false;

    _reconnectAttempts = 0;

    _isReconnectScheduled = false;

    _terminatedSessionToken = null;

    _terminatedCallId = null;

    _subscribeToCallDocument(
      callId: normalizedCallId,
      sessionToken: sessionToken,
    );
  }

  // =============================================================
  // RESTART LISTENING
  // =============================================================

  void restartListening(String callId) {
    if (_isDisposed) {
      return;
    }

    final String normalizedCallId = callId.trim();

    if (normalizedCallId.isEmpty) {
      return;
    }

    stopListening();

    startListening(normalizedCallId);
  }

  // =============================================================
  // STOP LISTENING
  // =============================================================

  void stopListening() {
    _stopActiveSession(clearQueue: true, clearCachedValues: true);
  }

  // =============================================================
  // PAUSE
  // =============================================================

  void pauseListening() {
    if (_isDisposed || !isListening || _isPaused) {
      return;
    }

    _isPaused = true;

    _cancelReconnectTimer(resetAttempts: false);

    final StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>?
    subscription = currentSubscription;

    if (subscription != null && !subscription.isPaused) {
      subscription.pause();
    }
  }

  // =============================================================
  // RESUME
  // =============================================================

  void resumeListening() {
    if (_isDisposed || !isListening || !_isPaused) {
      return;
    }

    _isPaused = false;

    final StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>?
    subscription = currentSubscription;

    if (subscription != null && subscription.isPaused) {
      subscription.resume();

      return;
    }

    final String? callId = currentCallId;

    if (callId == null) {
      return;
    }

    _subscribeToCallDocument(
      callId: callId,
      sessionToken: _sessionGenerationId,
    );
  }

  // =============================================================
  // SESSION VALIDATION
  // =============================================================

  bool _isSessionActive({required String callId, required int sessionToken}) {
    return !_isDisposed &&
        isListening &&
        !_isPaused &&
        currentCallId == callId &&
        _sessionGenerationId == sessionToken;
  }

  bool _isSubscriptionCurrent({
    required String callId,
    required int sessionToken,
    required int subscriptionToken,
  }) {
    return _isSessionActive(callId: callId, sessionToken: sessionToken) &&
        _subscriptionGenerationId == subscriptionToken;
  }

  // =============================================================
  // FIRESTORE SUBSCRIPTION
  // =============================================================

  void _subscribeToCallDocument({
    required String callId,
    required int sessionToken,
  }) {
    if (!_isSessionActive(callId: callId, sessionToken: sessionToken)) {
      return;
    }

    // -----------------------------------------------------------
    // CRITICAL RACE FIX
    //
    // Invalidate callbacks belonging to the previous listener
    // BEFORE cancellation and BEFORE installing its replacement.
    // -----------------------------------------------------------

    final int subscriptionToken = ++_subscriptionGenerationId;

    final StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>?
    previousSubscription = currentSubscription;

    currentSubscription = null;

    if (previousSubscription != null) {
      unawaited(
        previousSubscription.cancel().catchError((Object error) {
          debugPrint(
            'JR CALL [CallListenerService] '
            'old subscription cancellation error: $error',
          );
        }),
      );
    }

    if (!_isSubscriptionCurrent(
      callId: callId,
      sessionToken: sessionToken,
      subscriptionToken: subscriptionToken,
    )) {
      return;
    }

    currentSubscription = listenCall(callId).listen(
      (DocumentSnapshot<Map<String, dynamic>> snapshot) {
        if (!_isSubscriptionCurrent(
          callId: callId,
          sessionToken: sessionToken,
          subscriptionToken: subscriptionToken,
        )) {
          return;
        }

        _markListenerHealthy();

        try {
          _processSnapshot(
            snapshot: snapshot,
            callId: callId,
            sessionToken: sessionToken,
          );
        } catch (error, stackTrace) {
          _reportError(
            error,
            stackTrace: stackTrace,
            source: 'snapshot processing',
          );
        }
      },
      onError: (Object error, StackTrace stackTrace) {
        if (!_isSubscriptionCurrent(
          callId: callId,
          sessionToken: sessionToken,
          subscriptionToken: subscriptionToken,
        )) {
          return;
        }

        _reportError(
          error,
          stackTrace: stackTrace,
          source: 'Firestore call stream',
        );

        if (_isRetryableListenerError(error)) {
          _scheduleReconnect(callId: callId, sessionToken: sessionToken);
        } else {
          _stopFailedListenerSession(
            callId: callId,
            sessionToken: sessionToken,
          );
        }
      },
      onDone: () {
        if (!_isSubscriptionCurrent(
          callId: callId,
          sessionToken: sessionToken,
          subscriptionToken: subscriptionToken,
        )) {
          return;
        }

        _scheduleReconnect(callId: callId, sessionToken: sessionToken);
      },
      cancelOnError: true,
    );
  }

  // =============================================================
  // LISTENER ERROR CLASSIFICATION
  // =============================================================

  bool _isRetryableListenerError(Object error) {
    if (error is! FirebaseException) {
      return false;
    }

    switch (error.code.trim().toLowerCase()) {
      case 'aborted':
      case 'cancelled':
      case 'deadline-exceeded':
      case 'internal':
      case 'resource-exhausted':
      case 'unavailable':
      case 'unknown':
        return true;

      // Permanent/config/security errors must not enter a blind
      // reconnect loop.
      case 'permission-denied':
      case 'unauthenticated':
      case 'failed-precondition':
      case 'invalid-argument':
      case 'not-found':
      case 'already-exists':
      case 'out-of-range':
      case 'unimplemented':
      case 'data-loss':
        return false;

      default:
        return false;
    }
  }

  void _stopFailedListenerSession({
    required String callId,
    required int sessionToken,
  }) {
    if (!_isSessionActive(callId: callId, sessionToken: sessionToken)) {
      return;
    }

    _stopActiveSession(clearQueue: false, clearCachedValues: false);
  }

  // =============================================================
  // SNAPSHOT PROCESSING
  // =============================================================

  void _processSnapshot({
    required DocumentSnapshot<Map<String, dynamic>> snapshot,
    required String callId,
    required int sessionToken,
  }) {
    if (!snapshot.exists) {
      _handleDeletedCall(callId: callId, sessionToken: sessionToken);

      return;
    }

    final Map<String, dynamic>? data = snapshot.data();

    if (data == null) {
      return;
    }

    final String? rawStatus = _readNonEmptyString(data[CallFields.status]);

    final String? status = rawStatus?.toLowerCase();

    final bool terminal = status != null && CallStatusValues.isTerminal(status);

    // -----------------------------------------------------------
    // STATUS FIRST
    // -----------------------------------------------------------

    if (status != null && status != lastStatus) {
      lastStatus = status;

      _enqueueEvent(
        _CallListenerEvent(
          type: _CallListenerEventType.status,
          payload: status,
          sessionToken: sessionToken,
          callId: callId,
          deliverAfterTermination: terminal,
        ),
      );
    }

    // -----------------------------------------------------------
    // TERMINAL STATE
    //
    // Once terminal, no new SDP/state/recovery event from this
    // snapshot should be applied.
    // -----------------------------------------------------------

    if (terminal) {
      _handleTerminalCall(callId: callId, sessionToken: sessionToken);

      return;
    }

    // -----------------------------------------------------------
    // OFFER
    // -----------------------------------------------------------

    _processSessionDescription(
      rawDescription: data[CallFields.offer],
      previousDescription: lastOffer,
      expectedType: 'offer',
      updateCache: (Map<String, dynamic> description) {
        lastOffer = description;
      },
      eventType: _CallListenerEventType.offer,
      callId: callId,
      sessionToken: sessionToken,
    );

    // -----------------------------------------------------------
    // ANSWER
    // -----------------------------------------------------------

    _processSessionDescription(
      rawDescription: data[CallFields.answer],
      previousDescription: lastAnswer,
      expectedType: 'answer',
      updateCache: (Map<String, dynamic> description) {
        lastAnswer = description;
      },
      eventType: _CallListenerEventType.answer,
      callId: callId,
      sessionToken: sessionToken,
    );

    // -----------------------------------------------------------
    // CONNECTION STATE
    // -----------------------------------------------------------

    _processStringState(
      rawValue: data[CallFields.connectionState],
      previousValue: _lastConnectionState,
      updateCache: (String value) {
        _lastConnectionState = value;
      },
      eventType: _CallListenerEventType.connectionState,
      callId: callId,
      sessionToken: sessionToken,
    );

    // -----------------------------------------------------------
    // ICE CONNECTION STATE
    // -----------------------------------------------------------

    _processStringState(
      rawValue: data[CallFields.iceConnectionState],
      previousValue: _lastIceConnectionState,
      updateCache: (String value) {
        _lastIceConnectionState = value;
      },
      eventType: _CallListenerEventType.iceConnectionState,
      callId: callId,
      sessionToken: sessionToken,
    );

    // -----------------------------------------------------------
    // SIGNALING STATE
    // -----------------------------------------------------------

    _processStringState(
      rawValue: data[CallFields.signalingState],
      previousValue: _lastSignalingState,
      updateCache: (String value) {
        _lastSignalingState = value;
      },
      eventType: _CallListenerEventType.signalingState,
      callId: callId,
      sessionToken: sessionToken,
    );

    // -----------------------------------------------------------
    // ICE GATHERING STATE
    // -----------------------------------------------------------

    _processStringState(
      rawValue: data[CallFields.iceGatheringState],
      previousValue: _lastIceGatheringState,
      updateCache: (String value) {
        _lastIceGatheringState = value;
      },
      eventType: _CallListenerEventType.iceGatheringState,
      callId: callId,
      sessionToken: sessionToken,
    );

    // -----------------------------------------------------------
    // NETWORK RECOVERED
    // -----------------------------------------------------------

    _processNetworkRecovered(
      data[CallFields.networkRecovered],
      callId: callId,
      sessionToken: sessionToken,
    );

    // -----------------------------------------------------------
    // ICE RESTART COUNT
    // -----------------------------------------------------------

    _processIceRestartCount(
      data[CallFields.iceRestartCount],
      callId: callId,
      sessionToken: sessionToken,
    );
  }

  // =============================================================
  // SESSION DESCRIPTION PROCESSING
  // =============================================================

  void _processSessionDescription({
    required Object? rawDescription,
    required Map<String, dynamic>? previousDescription,
    required String expectedType,
    required ValueChanged<Map<String, dynamic>> updateCache,
    required _CallListenerEventType eventType,
    required String callId,
    required int sessionToken,
  }) {
    final Map<String, dynamic>? description = _normalizeMap(rawDescription);

    if (description == null ||
        !_isValidSessionDescription(description, expectedType: expectedType) ||
        _sessionDescriptionsEqual(previousDescription, description)) {
      return;
    }

    final String sdp = _readNonEmptyString(description[CallFields.sdp])!;

    final String type = _readNonEmptyString(
      description[CallFields.type],
    )!.toLowerCase();

    final Map<String, dynamic> immutableDescription =
        Map<String, dynamic>.unmodifiable(<String, dynamic>{
          CallFields.sdp: sdp,
          CallFields.type: type,
        });

    updateCache(immutableDescription);

    _enqueueEvent(
      _CallListenerEvent(
        type: eventType,
        payload: immutableDescription,
        sessionToken: sessionToken,
        callId: callId,
      ),
    );
  }

  // =============================================================
  // STRING STATE PROCESSING
  // =============================================================

  void _processStringState({
    required Object? rawValue,
    required String? previousValue,
    required ValueChanged<String> updateCache,
    required _CallListenerEventType eventType,
    required String callId,
    required int sessionToken,
  }) {
    final String? raw = _readNonEmptyString(rawValue);

    if (raw == null) {
      return;
    }

    final String value = raw.toLowerCase();

    if (value == previousValue) {
      return;
    }

    updateCache(value);

    _enqueueEvent(
      _CallListenerEvent(
        type: eventType,
        payload: value,
        sessionToken: sessionToken,
        callId: callId,
      ),
    );
  }

  // =============================================================
  // NETWORK RECOVERY PROCESSING
  // =============================================================

  void _processNetworkRecovered(
    Object? rawValue, {
    required String callId,
    required int sessionToken,
  }) {
    if (rawValue is! bool || rawValue == _lastNetworkRecovered) {
      return;
    }

    _lastNetworkRecovered = rawValue;

    if (!rawValue) {
      return;
    }

    _enqueueEvent(
      _CallListenerEvent(
        type: _CallListenerEventType.networkRecovered,
        sessionToken: sessionToken,
        callId: callId,
      ),
    );
  }

  // =============================================================
  // ICE RESTART PROCESSING
  // =============================================================

  void _processIceRestartCount(
    Object? rawValue, {
    required String callId,
    required int sessionToken,
  }) {
    final int? restartCount = _readInteger(rawValue);

    if (restartCount == null ||
        restartCount < 0 ||
        restartCount <= _lastIceRestartCount) {
      return;
    }

    final int missedRestartEvents = restartCount - _lastIceRestartCount;

    _lastIceRestartCount = restartCount;

    for (int index = 0; index < missedRestartEvents; index++) {
      _enqueueEvent(
        _CallListenerEvent(
          type: _CallListenerEventType.iceRestart,
          sessionToken: sessionToken,
          callId: callId,
        ),
      );
    }
  }

  // =============================================================
  // TERMINAL CALL
  // =============================================================

  void _handleTerminalCall({
    required String callId,
    required int sessionToken,
  }) {
    if (!_isSessionActive(callId: callId, sessionToken: sessionToken)) {
      return;
    }

    _enqueueEvent(
      _CallListenerEvent(
        type: _CallListenerEventType.callEnded,
        sessionToken: sessionToken,
        callId: callId,
        deliverAfterTermination: true,
      ),
    );

    _terminateSessionPreservingTerminalEvents(
      callId: callId,
      sessionToken: sessionToken,
    );
  }

  // =============================================================
  // DELETED CALL
  // =============================================================

  void _handleDeletedCall({required String callId, required int sessionToken}) {
    if (!_isSessionActive(callId: callId, sessionToken: sessionToken)) {
      return;
    }

    _enqueueEvent(
      _CallListenerEvent(
        type: _CallListenerEventType.callDeleted,
        sessionToken: sessionToken,
        callId: callId,
        deliverAfterTermination: true,
      ),
    );

    _enqueueEvent(
      _CallListenerEvent(
        type: _CallListenerEventType.callEnded,
        sessionToken: sessionToken,
        callId: callId,
        deliverAfterTermination: true,
      ),
    );

    _terminateSessionPreservingTerminalEvents(
      callId: callId,
      sessionToken: sessionToken,
    );
  }

  // =============================================================
  // TERMINAL SESSION SHUTDOWN
  // =============================================================

  void _terminateSessionPreservingTerminalEvents({
    required String callId,
    required int sessionToken,
  }) {
    _cancelReconnectTimer();

    _terminatedSessionToken = sessionToken;

    _terminatedCallId = callId;

    isListening = false;

    _isPaused = false;

    currentCallId = null;

    // Invalidate both:
    // - old call-session callbacks
    // - old subscription callbacks
    _sessionGenerationId++;

    _subscriptionGenerationId++;

    final StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>?
    subscription = currentSubscription;

    currentSubscription = null;

    if (subscription != null) {
      unawaited(
        subscription.cancel().catchError((Object error) {
          debugPrint(
            'JR CALL [CallListenerService] '
            'terminal listener cancellation error: $error',
          );
        }),
      );
    }
  }

  // =============================================================
  // LISTENER RECONNECT
  // =============================================================

  void _scheduleReconnect({required String callId, required int sessionToken}) {
    if (!_isSessionActive(callId: callId, sessionToken: sessionToken) ||
        _isReconnectScheduled) {
      return;
    }

    if (_reconnectAttempts >= _maximumReconnectAttempts) {
      _reportError(
        StateError('Maximum Firestore listener reconnect attempts reached.'),
        source: 'listener recovery',
      );

      stopListening();

      return;
    }

    _reconnectAttempts++;

    _isReconnectScheduled = true;

    final Duration reconnectDelay = _calculateReconnectDelay(
      _reconnectAttempts,
    );

    debugPrint(
      'JR CALL [CallListenerService]: reconnect '
      '$_reconnectAttempts/$_maximumReconnectAttempts '
      'in ${reconnectDelay.inSeconds}s.',
    );

    _reconnectTimer?.cancel();

    _reconnectTimer = Timer(reconnectDelay, () {
      _reconnectTimer = null;

      _isReconnectScheduled = false;

      if (!_isSessionActive(callId: callId, sessionToken: sessionToken)) {
        return;
      }

      _subscribeToCallDocument(callId: callId, sessionToken: sessionToken);
    });
  }

  Duration _calculateReconnectDelay(int attempt) {
    int milliseconds = _initialReconnectDelay.inMilliseconds;

    for (int index = 1; index < attempt; index++) {
      milliseconds *= 2;

      if (milliseconds >= _maximumReconnectDelay.inMilliseconds) {
        milliseconds = _maximumReconnectDelay.inMilliseconds;

        break;
      }
    }

    return Duration(milliseconds: milliseconds);
  }

  void _markListenerHealthy() {
    _reconnectAttempts = 0;

    _isReconnectScheduled = false;

    _reconnectTimer?.cancel();

    _reconnectTimer = null;
  }

  void _cancelReconnectTimer({bool resetAttempts = true}) {
    _reconnectTimer?.cancel();

    _reconnectTimer = null;

    _isReconnectScheduled = false;

    if (resetAttempts) {
      _reconnectAttempts = 0;
    }
  }

  // =============================================================
  // EVENT QUEUE
  // =============================================================

  void _enqueueEvent(_CallListenerEvent event) {
    if (_isDisposed) {
      return;
    }

    _eventQueue.addLast(event);

    if (!_isProcessingQueue) {
      scheduleMicrotask(_processEventQueue);
    }
  }

  void _processEventQueue() {
    if (_isDisposed || _isProcessingQueue) {
      return;
    }

    _isProcessingQueue = true;

    try {
      while (_eventQueue.isNotEmpty && !_isDisposed) {
        final _CallListenerEvent event = _eventQueue.removeFirst();

        if (!_eventCanBeDelivered(event)) {
          continue;
        }

        try {
          _dispatchEvent(event);
        } catch (error, stackTrace) {
          _reportError(error, stackTrace: stackTrace, source: 'event queue');
        }
      }
    } finally {
      _isProcessingQueue = false;

      if (_eventQueue.isNotEmpty && !_isDisposed) {
        scheduleMicrotask(_processEventQueue);
      }
    }
  }

  bool _eventCanBeDelivered(_CallListenerEvent event) {
    if (event.sessionToken == _sessionGenerationId) {
      return true;
    }

    if (!event.deliverAfterTermination) {
      return false;
    }

    return _terminatedSessionToken == event.sessionToken &&
        _terminatedCallId == event.callId;
  }

  // =============================================================
  // EVENT DISPATCH
  // =============================================================

  void _dispatchEvent(_CallListenerEvent event) {
    switch (event.type) {
      case _CallListenerEventType.status:
        _safeValueCallback(onStatusChanged, event.payload! as String);
        break;

      case _CallListenerEventType.offer:
        _safeValueCallback(
          onOfferReceived,
          event.payload! as Map<String, dynamic>,
        );
        break;

      case _CallListenerEventType.answer:
        _safeValueCallback(
          onAnswerReceived,
          event.payload! as Map<String, dynamic>,
        );
        break;

      case _CallListenerEventType.connectionState:
        _safeValueCallback(onConnectionStateChanged, event.payload! as String);
        break;

      case _CallListenerEventType.iceConnectionState:
        _safeValueCallback(
          onIceConnectionStateChanged,
          event.payload! as String,
        );
        break;

      case _CallListenerEventType.signalingState:
        _safeValueCallback(onSignalingStateChanged, event.payload! as String);
        break;

      case _CallListenerEventType.iceGatheringState:
        _safeValueCallback(
          onIceGatheringStateChanged,
          event.payload! as String,
        );
        break;

      case _CallListenerEventType.networkRecovered:
        _safeCallback(onNetworkRecovered);
        break;

      case _CallListenerEventType.iceRestart:
        _safeCallback(onIceRestart);
        break;

      case _CallListenerEventType.callEnded:
        _safeCallback(onCallEnded);
        break;

      case _CallListenerEventType.callDeleted:
        _safeCallback(onCallDeleted);
        break;
    }
  }

  // =============================================================
  // PUBLIC CALL STREAM
  // =============================================================

  Stream<DocumentSnapshot<Map<String, dynamic>>> listenCall(String callId) {
    final String normalizedCallId = callId.trim();

    if (normalizedCallId.isEmpty) {
      return Stream<DocumentSnapshot<Map<String, dynamic>>>.error(
        ArgumentError.value(callId, 'callId', 'Call ID cannot be empty.'),
      );
    }

    return _signalingService.listenCall(normalizedCallId);
  }

  // =============================================================
  // PUBLIC STATUS STREAM
  // =============================================================

  Stream<String> listenCallStatus(String callId) {
    return listenCall(callId).map<String>((
      DocumentSnapshot<Map<String, dynamic>> snapshot,
    ) {
      if (!snapshot.exists) {
        return CallStatusValues.ended;
      }

      return _readNonEmptyString(
            snapshot.data()?[CallFields.status],
          )?.toLowerCase() ??
          CallStatusValues.ended;
    }).distinct();
  }

  // =============================================================
  // PUBLIC OFFER STREAM
  // =============================================================

  Stream<Map<String, dynamic>?> listenOffer(String callId) {
    return listenCall(callId)
        .map<Map<String, dynamic>?>((
          DocumentSnapshot<Map<String, dynamic>> snapshot,
        ) {
          if (!snapshot.exists) {
            return null;
          }

          final Map<String, dynamic>? offer = _normalizeMap(
            snapshot.data()?[CallFields.offer],
          );

          if (offer == null ||
              !_isValidSessionDescription(offer, expectedType: 'offer')) {
            return null;
          }

          return _normalizedImmutableDescription(offer);
        })
        .distinct(_nullableSessionDescriptionsEqual);
  }

  // =============================================================
  // PUBLIC ANSWER STREAM
  // =============================================================

  Stream<Map<String, dynamic>?> listenAnswer(String callId) {
    return listenCall(callId)
        .map<Map<String, dynamic>?>((
          DocumentSnapshot<Map<String, dynamic>> snapshot,
        ) {
          if (!snapshot.exists) {
            return null;
          }

          final Map<String, dynamic>? answer = _normalizeMap(
            snapshot.data()?[CallFields.answer],
          );

          if (answer == null ||
              !_isValidSessionDescription(answer, expectedType: 'answer')) {
            return null;
          }

          return _normalizedImmutableDescription(answer);
        })
        .distinct(_nullableSessionDescriptionsEqual);
  }

  // =============================================================
  // SAFE CALLBACK WRAPPERS
  // =============================================================

  void _safeCallback(VoidCallback? callback) {
    if (callback == null || _isDisposed) {
      return;
    }

    try {
      callback();
    } catch (error, stackTrace) {
      _reportError(error, stackTrace: stackTrace, source: 'callback');
    }
  }

  void _safeValueCallback<T>(ValueChanged<T>? callback, T value) {
    if (callback == null || _isDisposed) {
      return;
    }

    try {
      callback(value);
    } catch (error, stackTrace) {
      _reportError(error, stackTrace: stackTrace, source: 'value callback');
    }
  }

  // =============================================================
  // ERROR REPORTING
  // =============================================================

  void _reportError(
    Object error, {
    StackTrace? stackTrace,
    String source = 'CallListenerService',
  }) {
    debugPrint(
      'JR CALL [CallListenerService/$source] '
      'error: $error',
    );

    if (stackTrace != null) {
      debugPrintStack(
        label: 'JR CALL [CallListenerService/$source]',
        stackTrace: stackTrace,
      );
    }

    final ValueChanged<Object>? errorCallback = onError;

    if (_isDisposed || errorCallback == null || _isReportingError) {
      return;
    }

    _isReportingError = true;

    try {
      errorCallback(error);
    } catch (callbackError, callbackStackTrace) {
      debugPrint(
        'JR CALL [CallListenerService/onError] '
        'callback failed: $callbackError',
      );

      debugPrintStack(
        label: 'JR CALL [CallListenerService/onError]',
        stackTrace: callbackStackTrace,
      );
    } finally {
      _isReportingError = false;
    }
  }

  // =============================================================
  // STRING NORMALIZATION
  // =============================================================

  String? _readNonEmptyString(Object? value) {
    if (value is! String) {
      return null;
    }

    final String normalizedValue = value.trim();

    return normalizedValue.isEmpty ? null : normalizedValue;
  }

  // =============================================================
  // INTEGER NORMALIZATION
  // =============================================================

  int? _readInteger(Object? value) {
    if (value is int) {
      return value;
    }

    if (value is num && value.isFinite) {
      return value.toInt();
    }

    if (value is String) {
      return int.tryParse(value.trim());
    }

    return null;
  }

  // =============================================================
  // MAP NORMALIZATION
  // =============================================================

  Map<String, dynamic>? _normalizeMap(Object? value) {
    if (value is Map<String, dynamic>) {
      return Map<String, dynamic>.from(value);
    }

    if (value is Map) {
      final Map<String, dynamic> normalizedMap = <String, dynamic>{};

      for (final MapEntry<dynamic, dynamic> entry in value.entries) {
        final Object? key = entry.key;

        if (key is! String) {
          return null;
        }

        normalizedMap[key] = entry.value;
      }

      return normalizedMap;
    }

    return null;
  }

  // =============================================================
  // SDP VALIDATION
  // =============================================================

  bool _isValidSessionDescription(
    Map<String, dynamic> description, {
    String? expectedType,
  }) {
    final String? sdp = _readNonEmptyString(description[CallFields.sdp]);

    final String? rawType = _readNonEmptyString(description[CallFields.type]);

    if (sdp == null || rawType == null) {
      return false;
    }

    final String type = rawType.toLowerCase();

    if (expectedType != null && type != expectedType.toLowerCase()) {
      return false;
    }

    return type == 'offer' || type == 'answer';
  }

  // =============================================================
  // IMMUTABLE SDP COPY
  // =============================================================

  Map<String, dynamic> _normalizedImmutableDescription(
    Map<String, dynamic> description,
  ) {
    return Map<String, dynamic>.unmodifiable(<String, dynamic>{
      CallFields.sdp: _readNonEmptyString(description[CallFields.sdp])!,
      CallFields.type: _readNonEmptyString(
        description[CallFields.type],
      )!.toLowerCase(),
    });
  }

  // =============================================================
  // SDP EQUALITY
  // =============================================================

  bool _sessionDescriptionsEqual(
    Map<String, dynamic>? first,
    Map<String, dynamic>? second,
  ) {
    if (identical(first, second)) {
      return true;
    }

    if (first == null || second == null) {
      return false;
    }

    final String? firstSdp = _readNonEmptyString(first[CallFields.sdp]);

    final String? secondSdp = _readNonEmptyString(second[CallFields.sdp]);

    final String? firstType = _readNonEmptyString(
      first[CallFields.type],
    )?.toLowerCase();

    final String? secondType = _readNonEmptyString(
      second[CallFields.type],
    )?.toLowerCase();

    return firstSdp == secondSdp && firstType == secondType;
  }

  bool _nullableSessionDescriptionsEqual(
    Map<String, dynamic>? first,
    Map<String, dynamic>? second,
  ) {
    return _sessionDescriptionsEqual(first, second);
  }

  // =============================================================
  // RESET
  // =============================================================

  void reset() {
    _stopActiveSession(clearQueue: true, clearCachedValues: true);

    _clearCallbacks();
  }

  // =============================================================
  // ACTIVE SESSION CLEANUP
  // =============================================================

  void _stopActiveSession({
    required bool clearQueue,
    required bool clearCachedValues,
  }) {
    _sessionGenerationId++;

    _subscriptionGenerationId++;

    _cancelReconnectTimer();

    isListening = false;

    _isPaused = false;

    currentCallId = null;

    _terminatedSessionToken = null;

    _terminatedCallId = null;

    final StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>?
    subscription = currentSubscription;

    currentSubscription = null;

    if (subscription != null) {
      unawaited(
        subscription.cancel().catchError((Object error) {
          debugPrint(
            'JR CALL [CallListenerService] '
            'subscription cancellation error: $error',
          );
        }),
      );
    }

    if (clearQueue) {
      _eventQueue.clear();
    }

    if (clearCachedValues) {
      _clearCachedValues();
    }
  }

  // =============================================================
  // CACHED VALUE CLEANUP
  // =============================================================

  void _clearCachedValues() {
    lastStatus = null;

    lastOffer = null;

    lastAnswer = null;

    _lastConnectionState = null;

    _lastIceConnectionState = null;

    _lastSignalingState = null;

    _lastIceGatheringState = null;

    _lastNetworkRecovered = false;

    _lastIceRestartCount = 0;
  }

  // =============================================================
  // CALLBACK CLEANUP
  // =============================================================

  void _clearCallbacks() {
    onStatusChanged = null;

    onOfferReceived = null;

    onAnswerReceived = null;

    onCallEnded = null;

    onCallDeleted = null;

    onConnectionStateChanged = null;

    onIceConnectionStateChanged = null;

    onSignalingStateChanged = null;

    onIceGatheringStateChanged = null;

    onNetworkRecovered = null;

    onIceRestart = null;

    onError = null;
  }

  // =============================================================
  // DISPOSE
  // =============================================================

  /// After dispose(), initialize() is required before singleton reuse.
  void dispose() {
    if (_isDisposed) {
      return;
    }

    reset();

    _isDisposed = true;
  }
}

// ===============================================================
// END OF FILE
//
// File:
// call_listener_service.dart
//
// Location:
// lib/services/call/call_listener_service.dart
//
// FINAL REPAIRS:
//
// ✓ SignalingService remains sole Firestore-access owner.
//
// ✓ No Firestore write duplicated.
//
// ✓ No WebRTC ownership duplicated.
//
// ✓ No ICE ownership duplicated.
//
// ✓ No CallService lifecycle duplicated.
//
// ✓ Existing public callbacks preserved.
//
// ✓ Existing CallFields preserved.
//
// ✓ Existing CallStatusValues preserved.
//
// ✓ One active current subscription.
//
// ✓ Separate subscription-generation guard added.
//
// ✓ Old cancelled subscription cannot affect replacement listener.
//
// ✓ Old subscription error cannot create a false reconnect.
//
// ✓ Old subscription completion cannot create a false reconnect.
//
// ✓ Duplicate status filtered.
//
// ✓ Duplicate offer filtered.
//
// ✓ Duplicate answer filtered.
//
// ✓ Duplicate connection states filtered.
//
// ✓ Terminal status delivered before lifecycle cleanup.
//
// ✓ Terminal callEnded preserved after synchronous invalidation.
//
// ✓ Deleted call correctly emits callDeleted + callEnded.
//
// ✓ Stale terminal events cannot enter the next call.
//
// ✓ Bounded exponential reconnect preserved.
//
// ✓ Transient Firestore error retry supported.
//
// ✓ Permanent Firestore/security/config errors not blindly retried.
//
// ✓ Offer/answer validation preserved.
//
// ✓ ICE restart count ordering preserved.
//
// ✓ Network-recovery event preserved.
//
// ✓ Queue dispatch remains deterministic.
//
// STATUS:
// CALL LISTENER LOGIC FINALIZED.
//
// NEXT FILE:
// call_service.dart
//
// Location:
// lib/services/call/call_service.dart
//
// IMPORTANT:
// Do not build APK yet.
// One final dependency pass must compare this exact listener against
// the current CallService before two-device Voice/Video testing.
// ===============================================================
